name: CI

on:
  # main 브랜치로 pull request 일 때만 수행한다.
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        # install 옵션에 대해서는 yarn 공식 문서를 참고해주세요.
        # https://yarnpkg.com/cli/install
        run: yarn install --immutable --immutable-cache

      - name: Check Unit Test
        # unut test 검증
        run: yarn test run
